#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_FP_Copy

#include "Basic.hpp"

#include "ABP_FP_Copy_classes.hpp"
#include "ABP_FP_Copy_parameters.hpp"


SDK_NAMESPACE_START

// Function ABP_FP_Copy.ABP_FP_Copy_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph                                              (Parm, OutParm, NoDestructor)

void UABP_FP_Copy_C::AnimGraph(struct FPoseLink* AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_FP_Copy_C", "AnimGraph");

	Params::ABP_FP_Copy_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph != nullptr)
		*AnimGraph = std::move(Parms.AnimGraph);
}


SDK_NAMESPACE_END
