#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BootsUpgrade

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct BootsUpgrade.BootsUpgrade
// 0x0040 (0x0040 - 0x0000)
struct FBootsUpgrade final
{
public:
	class FText                                   Name_13_95363D7149C3B00B4D41E8A454B392E2;          // 0x0000(0x0010)(Edit, BlueprintVisible)
	class FText                                   Description_6_9F0EA8C34A0C7657F7C5C3B62FFFB692;    // 0x0010(0x0010)(Edit, BlueprintVisible)
	class UTexture2D*                             icon_9_606ACEF44465402FFAF528B467F63476;           // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        Speed_12_DCDA50064277CD1B06DC0082AD7F3017;         // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Price_16_6FA95D78456A3184DA5A8FA88907101F;         // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   nextup_20_EEEEB06B43C3F625F251D29B816C5A11;        // 0x0034(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FBootsUpgrade;

SDK_NAMESPACE_END
