#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FirstPersonPlayerController

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FirstPersonPlayerController.BP_FirstPersonPlayerController_C
// 0x0010 (0x0748 - 0x0738)
class ABP_FirstPersonPlayerController_C final : public APlayerController
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0738(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UClass*                                 Touch_Controls_Widget_Class;                       // 0x0740(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_FirstPersonPlayerController(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FirstPersonPlayerController_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FirstPersonPlayerController_C")
	}
	static class ABP_FirstPersonPlayerController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FirstPersonPlayerController_C>();
	}
};
DUMPER7_ASSERTS_ABP_FirstPersonPlayerController_C;

SDK_NAMESPACE_END
