#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FirstPersonPlayerController

#include "Basic.hpp"

#include "BP_FirstPersonPlayerController_classes.hpp"
#include "BP_FirstPersonPlayerController_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_FirstPersonPlayerController.BP_FirstPersonPlayerController_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_FirstPersonPlayerController_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FirstPersonPlayerController_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FirstPersonPlayerController.BP_FirstPersonPlayerController_C.ExecuteUbergraph_BP_FirstPersonPlayerController
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FirstPersonPlayerController_C::ExecuteUbergraph_BP_FirstPersonPlayerController(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FirstPersonPlayerController_C", "ExecuteUbergraph_BP_FirstPersonPlayerController");

	Params::BP_FirstPersonPlayerController_C_ExecuteUbergraph_BP_FirstPersonPlayerController Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
