#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DonutStoreNotebook

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass DonutStoreNotebook.DonutStoreNotebook_C
// 0x0030 (0x02D8 - 0x02A8)
class ADonutStoreNotebook_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCameraComponent*                       Camera;                                            // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ABP_FirstPersonCharacter_C*             Hrac;                                              // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UW_DonutStore_C*                        DonutHUD;                                          // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void Zobral_som_odpadok();
	void ZiskajHraca(class ABP_FirstPersonCharacter_C** Hrac);
	void UnlockLockPick();
	void Ukončil_som_Pickup_Predčasne();
	void Stop_timerEvent();
	void Spawnol_som_smeti();
	void ResumeTimer();
	void ResetKolkoDrzim();
	void RemoveDynamicEventTxt();
	void Refka_na_Progressbar(class UWB_RoundProgressBar_C** PB);
	void ReceiveBeginPlay();
	void PosliHodnotuLootu(double Váha_kg, double Hodnota);
	void KukamNaTeba(bool NE);
	void Kolko_je_spawned_smeti_(int32* Kolko_, int32* Kolko_je_max_);
	void Interakica();
	void ExecuteUbergraph_DonutStoreNotebook(int32 EntryPoint);
	void camera_back_to_norm();
	void Adrenaline_(int32 Amount___Max_3);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DonutStoreNotebook_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DonutStoreNotebook_C")
	}
	static class ADonutStoreNotebook_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADonutStoreNotebook_C>();
	}
};
DUMPER7_ASSERTS_ADonutStoreNotebook_C;

SDK_NAMESPACE_END
