#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: garbageTruckInv

#include "Basic.hpp"

#include "garbageTruckInv_classes.hpp"
#include "garbageTruckInv_parameters.hpp"


SDK_NAMESPACE_START

// Function garbageTruckInv.garbageTruckInv_C.Adrenaline+
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Amount___Max_3                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AgarbageTruckInv_C::Adrenaline_(int32 Amount___Max_3)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "Adrenaline+");

	Params::garbageTruckInv_C_Adrenaline_ Parms{};

	Parms.Amount___Max_3 = Amount___Max_3;

	UObject::ProcessEvent(Func, &Parms);
}


// Function garbageTruckInv.garbageTruckInv_C.ExecuteUbergraph_garbageTruckInv
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AgarbageTruckInv_C::ExecuteUbergraph_garbageTruckInv(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "ExecuteUbergraph_garbageTruckInv");

	Params::garbageTruckInv_C_ExecuteUbergraph_garbageTruckInv Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function garbageTruckInv.garbageTruckInv_C.find look at
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AgarbageTruckInv_C::find_look_at()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "find look at");

	UObject::ProcessEvent(Func, nullptr);
}


// Function garbageTruckInv.garbageTruckInv_C.InterakciaHold
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Kolko_Drzim_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AgarbageTruckInv_C::InterakciaHold(double Kolko_Drzim_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "InterakciaHold");

	Params::garbageTruckInv_C_InterakciaHold Parms{};

	Parms.Kolko_Drzim_0 = Kolko_Drzim_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function garbageTruckInv.garbageTruckInv_C.Interakica
// (Public, BlueprintCallable, BlueprintEvent)

void AgarbageTruckInv_C::Interakica()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "Interakica");

	UObject::ProcessEvent(Func, nullptr);
}


// Function garbageTruckInv.garbageTruckInv_C.Kolko je spawned smeti?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32*                                  Kolko_                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Kolko_je_max_                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AgarbageTruckInv_C::Kolko_je_spawned_smeti_(int32* Kolko_, int32* Kolko_je_max_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "Kolko je spawned smeti?");

	Params::garbageTruckInv_C_Kolko_je_spawned_smeti_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Kolko_ != nullptr)
		*Kolko_ = Parms.Kolko_;

	if (Kolko_je_max_ != nullptr)
		*Kolko_je_max_ = Parms.Kolko_je_max_;
}


// Function garbageTruckInv.garbageTruckInv_C.KukamNaTeba
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NE                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AgarbageTruckInv_C::KukamNaTeba(bool NE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "KukamNaTeba");

	Params::garbageTruckInv_C_KukamNaTeba Parms{};

	Parms.NE = NE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function garbageTruckInv.garbageTruckInv_C.Nastav Value Smetiarkseho auta
// (Public, BlueprintCallable, BlueprintEvent)

void AgarbageTruckInv_C::Nastav_Value_Smetiarkseho_auta()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "Nastav Value Smetiarkseho auta");

	UObject::ProcessEvent(Func, nullptr);
}


// Function garbageTruckInv.garbageTruckInv_C.PosliHodnotuLootu
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Váha_kg                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Hodnota_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AgarbageTruckInv_C::PosliHodnotuLootu(double Váha_kg, double Hodnota_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "PosliHodnotuLootu");

	Params::garbageTruckInv_C_PosliHodnotuLootu Parms{};

	Parms.Váha_kg = Váha_kg;
	Parms.Hodnota_0 = Hodnota_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function garbageTruckInv.garbageTruckInv_C.random value zase
// (Public, BlueprintCallable, BlueprintEvent)

void AgarbageTruckInv_C::random_value_zase()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "random value zase");

	UObject::ProcessEvent(Func, nullptr);
}


// Function garbageTruckInv.garbageTruckInv_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AgarbageTruckInv_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function garbageTruckInv.garbageTruckInv_C.Refka na Progressbar
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWB_RoundProgressBar_C**          PB                                                     (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void AgarbageTruckInv_C::Refka_na_Progressbar(class UWB_RoundProgressBar_C** PB)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "Refka na Progressbar");

	Params::garbageTruckInv_C_Refka_na_Progressbar Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PB != nullptr)
		*PB = Parms.PB;
}


// Function garbageTruckInv.garbageTruckInv_C.RemoveDynamicEventTxt
// (Public, BlueprintCallable, BlueprintEvent)

void AgarbageTruckInv_C::RemoveDynamicEventTxt()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "RemoveDynamicEventTxt");

	UObject::ProcessEvent(Func, nullptr);
}


// Function garbageTruckInv.garbageTruckInv_C.ResetKolkoDrzim
// (Public, BlueprintCallable, BlueprintEvent)

void AgarbageTruckInv_C::ResetKolkoDrzim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "ResetKolkoDrzim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function garbageTruckInv.garbageTruckInv_C.ResumeTimer
// (Public, BlueprintCallable, BlueprintEvent)

void AgarbageTruckInv_C::ResumeTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "ResumeTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function garbageTruckInv.garbageTruckInv_C.Spawnol som smeti
// (Public, BlueprintCallable, BlueprintEvent)

void AgarbageTruckInv_C::Spawnol_som_smeti()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "Spawnol som smeti");

	UObject::ProcessEvent(Func, nullptr);
}


// Function garbageTruckInv.garbageTruckInv_C.Stop timerEvent
// (Public, BlueprintCallable, BlueprintEvent)

void AgarbageTruckInv_C::Stop_timerEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "Stop timerEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function garbageTruckInv.garbageTruckInv_C.Timeline__FinishedFunc
// (BlueprintEvent)

void AgarbageTruckInv_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function garbageTruckInv.garbageTruckInv_C.Timeline__UpdateFunc
// (BlueprintEvent)

void AgarbageTruckInv_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function garbageTruckInv.garbageTruckInv_C.Ukončil som Pickup Predčasne
// (Public, BlueprintCallable, BlueprintEvent)

void AgarbageTruckInv_C::Ukončil_som_Pickup_Predčasne()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "Ukončil som Pickup Predčasne");

	UObject::ProcessEvent(Func, nullptr);
}


// Function garbageTruckInv.garbageTruckInv_C.Unesiem to?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool AgarbageTruckInv_C::Unesiem_to_()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "Unesiem to?");

	Params::garbageTruckInv_C_Unesiem_to_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function garbageTruckInv.garbageTruckInv_C.UnlockLockPick
// (Public, BlueprintCallable, BlueprintEvent)

void AgarbageTruckInv_C::UnlockLockPick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "UnlockLockPick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function garbageTruckInv.garbageTruckInv_C.ZiskajHraca
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_FirstPersonCharacter_C**      Hrac_0                                                 (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AgarbageTruckInv_C::ZiskajHraca(class ABP_FirstPersonCharacter_C** Hrac_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "ZiskajHraca");

	Params::garbageTruckInv_C_ZiskajHraca Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Hrac_0 != nullptr)
		*Hrac_0 = Parms.Hrac_0;
}


// Function garbageTruckInv.garbageTruckInv_C.Zobral som odpadok
// (Public, BlueprintCallable, BlueprintEvent)

void AgarbageTruckInv_C::Zobral_som_odpadok()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("garbageTruckInv_C", "Zobral som odpadok");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
