#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: garbageTruckInv

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass garbageTruckInv.garbageTruckInv_C
// 0x0090 (0x0338 - 0x02A8)
class AgarbageTruckInv_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetComponent*                       Widget;                                            // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box;                                               // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPaperSpriteComponent*                  PaperSprite;                                       // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_NewTrack_0_66E8BC9348FAF5B835A1DFA388E7A757; // 0x02D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline__Direction_66E8BC9348FAF5B835A1DFA388E7A757; // 0x02D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D5[0x3];                                      // 0x02D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline;                                          // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class ABP_FirstPersonCharacter_C*             Hrac;                                              // 0x02E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        Kolko_treba_drzat;                                 // 0x02E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Hodnota;                                           // 0x02F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        kolko_vazim;                                       // 0x02F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                start_loc;                                         // 0x0300(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Empty;                                             // 0x0318(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_319[0x7];                                      // 0x0319(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        MaxMaxWin;                                         // 0x0320(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Kolko_Drzim;                                       // 0x0328(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWB_RoundProgressBar_C*                 SELF_WB_Round_Progress_Bar;                        // 0x0330(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void Zobral_som_odpadok();
	void ZiskajHraca(class ABP_FirstPersonCharacter_C** Hrac);
	void UnlockLockPick();
	bool Unesiem_to_();
	void Ukončil_som_Pickup_Predčasne();
	void Timeline__UpdateFunc();
	void Timeline__FinishedFunc();
	void Stop_timerEvent();
	void Spawnol_som_smeti();
	void ResumeTimer();
	void ResetKolkoDrzim();
	void RemoveDynamicEventTxt();
	void Refka_na_Progressbar(class UWB_RoundProgressBar_C** PB);
	void ReceiveBeginPlay();
	void random_value_zase();
	void PosliHodnotuLootu(double Váha_kg, double Hodnota);
	void Nastav_Value_Smetiarkseho_auta();
	void KukamNaTeba(bool NE);
	void Kolko_je_spawned_smeti_(int32* Kolko_, int32* Kolko_je_max_);
	void Interakica();
	void InterakciaHold(double Kolko_Drzim);
	void find_look_at();
	void ExecuteUbergraph_garbageTruckInv(int32 EntryPoint);
	void Adrenaline_(int32 Amount___Max_3);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("garbageTruckInv_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"garbageTruckInv_C")
	}
	static class AgarbageTruckInv_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AgarbageTruckInv_C>();
	}
};
DUMPER7_ASSERTS_AgarbageTruckInv_C;

SDK_NAMESPACE_END
