#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GeometryMask

#include "Basic.hpp"

#include "GeometryMask_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function GeometryMask.GeometryMaskCanvas.GetColorChannel
// 0x0001 (0x0001 - 0x0000)
struct GeometryMaskCanvas_GetColorChannel final
{
public:
	EGeometryMaskColorChannel                     ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_GeometryMaskCanvas_GetColorChannel;

// Function GeometryMask.GeometryMaskCanvas.GetTexture
// 0x0008 (0x0008 - 0x0000)
struct GeometryMaskCanvas_GetTexture final
{
public:
	class UCanvasRenderTarget2D*                  ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_GeometryMaskCanvas_GetTexture;

// Function GeometryMask.GeometryMaskCanvasActor.GetTexture
// 0x0008 (0x0008 - 0x0000)
struct GeometryMaskCanvasActor_GetTexture final
{
public:
	class UCanvasRenderTarget2D*                  ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_GeometryMaskCanvasActor_GetTexture;

// Function GeometryMask.GeometryMaskCanvasReferenceComponentBase.GetTexture
// 0x0008 (0x0008 - 0x0000)
struct GeometryMaskCanvasReferenceComponentBase_GetTexture final
{
public:
	class UCanvasRenderTarget2D*                  ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_GeometryMaskCanvasReferenceComponentBase_GetTexture;

// Function GeometryMask.GeometryMaskCanvasReferenceComponentBase.ReceiveSetCanvas
// 0x0008 (0x0008 - 0x0000)
struct GeometryMaskCanvasReferenceComponentBase_ReceiveSetCanvas final
{
public:
	const class UGeometryMaskCanvas*              InCanvas;                                          // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_GeometryMaskCanvasReferenceComponentBase_ReceiveSetCanvas;

// Function GeometryMask.GeometryMaskSubsystem.GetDefaultCanvas
// 0x0008 (0x0008 - 0x0000)
struct GeometryMaskSubsystem_GetDefaultCanvas final
{
public:
	class UGeometryMaskCanvas*                    ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_GeometryMaskSubsystem_GetDefaultCanvas;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
