#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HoldKomunikalica

#include "Basic.hpp"

#include "HoldKomunikalica_classes.hpp"
#include "HoldKomunikalica_parameters.hpp"


SDK_NAMESPACE_START

// Function HoldKomunikalica.HoldKomunikalica_C.InterakciaHold
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Kolko_Drzim                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IHoldKomunikalica_C::InterakciaHold(double Kolko_Drzim)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("HoldKomunikalica_C", "InterakciaHold");

	Params::HoldKomunikalica_C_InterakciaHold Parms{};

	Parms.Kolko_Drzim = Kolko_Drzim;

	AsUObject()->ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
