#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HoldKomunikalica

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass HoldKomunikalica.HoldKomunikalica_C
// 0x0000 (0x0000 - 0x0000)
class IHoldKomunikalica_C final
{
public:
	void InterakciaHold(double Kolko_Drzim);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HoldKomunikalica_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HoldKomunikalica_C")
	}
	static class IHoldKomunikalica_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IHoldKomunikalica_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IHoldKomunikalica_C;

SDK_NAMESPACE_END
