#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HoldKomunikalica

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function HoldKomunikalica.HoldKomunikalica_C.InterakciaHold
// 0x0008 (0x0008 - 0x0000)
struct HoldKomunikalica_C_InterakciaHold final
{
public:
	double                                        Kolko_Drzim;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_HoldKomunikalica_C_InterakciaHold;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
