#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: invnetoryUpgrades

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct invnetoryUpgrades.invnetoryUpgrades
// 0x0040 (0x0040 - 0x0000)
struct FinvnetoryUpgrades final
{
public:
	class FText                                   Nameoftheupgrade_4_95363D7149C3B00B4D41E8A454B392E2; // 0x0000(0x0010)(Edit, BlueprintVisible)
	class FText                                   Description_6_9F0EA8C34A0C7657F7C5C3B62FFFB692;    // 0x0010(0x0010)(Edit, BlueprintVisible)
	class UTexture2D*                             icon_9_606ACEF44465402FFAF528B467F63476;           // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        KgMax_13_4B556A4D4D44BA91F97DB1B893964840;         // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Price_16_EC935B2047017F86927369A18C4291D6;         // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Nextup_19_994CD47B4B5A6B20310DF684468B4576;        // 0x0034(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FinvnetoryUpgrades;

SDK_NAMESPACE_END
