#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenuHUD

#include "Basic.hpp"

#include "MainMenuHUD_classes.hpp"
#include "MainMenuHUD_parameters.hpp"


SDK_NAMESPACE_START

// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_AntiAliasing+_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_AntiAliasing__K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_AntiAliasing+_K2Node_ComponentBoundEvent_18_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_AntiAliasing-_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_AntiAliasing__K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_AntiAliasing-_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_APPLYSETTING_K2Node_ComponentBoundEvent_19_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_APPLYSETTING_K2Node_ComponentBoundEvent_19_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_APPLYSETTING_K2Node_ComponentBoundEvent_19_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_APPLYSETTING_K2Node_ComponentBoundEvent_45_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_APPLYSETTING_K2Node_ComponentBoundEvent_45_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_APPLYSETTING_K2Node_ComponentBoundEvent_45_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_APPLYSETTING_K2Node_ComponentBoundEvent_46_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_APPLYSETTING_K2Node_ComponentBoundEvent_46_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_APPLYSETTING_K2Node_ComponentBoundEvent_46_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_BENCHMARK_K2Node_ComponentBoundEvent_23_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_BENCHMARK_K2Node_ComponentBoundEvent_23_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_BENCHMARK_K2Node_ComponentBoundEvent_23_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_ExitFromPlay_K2Node_ComponentBoundEvent_49_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_ExitFromPlay_K2Node_ComponentBoundEvent_49_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_ExitFromPlay_K2Node_ComponentBoundEvent_49_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_ExitFromPlay_K2Node_ComponentBoundEvent_50_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_ExitFromPlay_K2Node_ComponentBoundEvent_50_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_ExitFromPlay_K2Node_ComponentBoundEvent_50_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_ExitFromPlay_K2Node_ComponentBoundEvent_51_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_ExitFromPlay_K2Node_ComponentBoundEvent_51_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_ExitFromPlay_K2Node_ComponentBoundEvent_51_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_ExitFromSettings_K2Node_ComponentBoundEvent_42_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_ExitFromSettings_K2Node_ComponentBoundEvent_42_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_ExitFromSettings_K2Node_ComponentBoundEvent_42_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_ExitFromSettings_K2Node_ComponentBoundEvent_43_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_ExitFromSettings_K2Node_ComponentBoundEvent_43_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_ExitFromSettings_K2Node_ComponentBoundEvent_43_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_ExitFromSettings_K2Node_ComponentBoundEvent_44_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_ExitFromSettings_K2Node_ComponentBoundEvent_44_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_ExitFromSettings_K2Node_ComponentBoundEvent_44_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_FrameRateGap+_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_FrameRateGap__K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_FrameRateGap+_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_FrameRateGap-_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_FrameRateGap__K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_FrameRateGap-_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_LoadGame_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_LoadGame_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_LoadGame_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_LoadGame_K2Node_ComponentBoundEvent_34_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_LoadGame_K2Node_ComponentBoundEvent_34_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_LoadGame_K2Node_ComponentBoundEvent_34_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_LoadGame_K2Node_ComponentBoundEvent_35_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_LoadGame_K2Node_ComponentBoundEvent_35_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_LoadGame_K2Node_ComponentBoundEvent_35_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_MusicVolunme_K2Node_ComponentBoundEvent_31_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_MusicVolunme_K2Node_ComponentBoundEvent_31_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_MusicVolunme_K2Node_ComponentBoundEvent_31_OnFloatValueChangedEvent__DelegateSignature");

	Params::MainMenuHUD_C_BndEvt__MainMenuHUD_MusicVolunme_K2Node_ComponentBoundEvent_31_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_Newgame_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_Newgame_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_Newgame_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_Newgame_K2Node_ComponentBoundEvent_32_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_Newgame_K2Node_ComponentBoundEvent_32_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_Newgame_K2Node_ComponentBoundEvent_32_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_Newgame_K2Node_ComponentBoundEvent_33_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_Newgame_K2Node_ComponentBoundEvent_33_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_Newgame_K2Node_ComponentBoundEvent_33_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_play_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_play_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_play_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_play_K2Node_ComponentBoundEvent_24_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_play_K2Node_ComponentBoundEvent_24_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_play_K2Node_ComponentBoundEvent_24_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_play_K2Node_ComponentBoundEvent_25_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_play_K2Node_ComponentBoundEvent_25_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_play_K2Node_ComponentBoundEvent_25_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_quit_K2Node_ComponentBoundEvent_29_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_quit_K2Node_ComponentBoundEvent_29_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_quit_K2Node_ComponentBoundEvent_29_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_quit_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_quit_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_quit_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_quit_K2Node_ComponentBoundEvent_30_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_quit_K2Node_ComponentBoundEvent_30_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_quit_K2Node_ComponentBoundEvent_30_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_Resolution+_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_Resolution__K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_Resolution+_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_Resolution-_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_Resolution__K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_Resolution-_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_Sensitivity_K2Node_ComponentBoundEvent_32_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_Sensitivity_K2Node_ComponentBoundEvent_32_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_Sensitivity_K2Node_ComponentBoundEvent_32_OnFloatValueChangedEvent__DelegateSignature");

	Params::MainMenuHUD_C_BndEvt__MainMenuHUD_Sensitivity_K2Node_ComponentBoundEvent_32_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_settings_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_settings_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_settings_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_settings_K2Node_ComponentBoundEvent_27_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_settings_K2Node_ComponentBoundEvent_27_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_settings_K2Node_ComponentBoundEvent_27_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_settings_K2Node_ComponentBoundEvent_28_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_settings_K2Node_ComponentBoundEvent_28_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_settings_K2Node_ComponentBoundEvent_28_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_Shader+_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_Shader__K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_Shader+_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_Shader-_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_Shader__K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_Shader-_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_Shadow+_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_Shadow__K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_Shadow+_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_Shadow-_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_Shadow__K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_Shadow-_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_Texture+_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_Texture__K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_Texture+_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_Texture-_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_Texture__K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_Texture-_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_VolumeSoundEffects_K2Node_ComponentBoundEvent_20_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_VolumeSoundEffects_K2Node_ComponentBoundEvent_20_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_VolumeSoundEffects_K2Node_ComponentBoundEvent_20_OnFloatValueChangedEvent__DelegateSignature");

	Params::MainMenuHUD_C_BndEvt__MainMenuHUD_VolumeSoundEffects_K2Node_ComponentBoundEvent_20_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_Vsync+_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_Vsync__K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_Vsync+_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_Vsync-_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_Vsync__K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_Vsync-_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_windows+_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_windows__K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_windows+_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_windows-_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_windows__K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_windows-_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.BndEvt__MainMenuHUD_ZHOD_K2Node_ComponentBoundEvent_47_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UMainMenuHUD_C::BndEvt__MainMenuHUD_ZHOD_K2Node_ComponentBoundEvent_47_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "BndEvt__MainMenuHUD_ZHOD_K2Node_ComponentBoundEvent_47_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMainMenuHUD_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.ExecuteUbergraph_MainMenuHUD
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainMenuHUD_C::ExecuteUbergraph_MainMenuHUD(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "ExecuteUbergraph_MainMenuHUD");

	Params::MainMenuHUD_C_ExecuteUbergraph_MainMenuHUD Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainMenuHUD.MainMenuHUD_C.ExitFromSettingss
// (BlueprintCallable, BlueprintEvent)

void UMainMenuHUD_C::ExitFromSettingss()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "ExitFromSettingss");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.get antialiasing
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMainMenuHUD_C::get_antialiasing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "get antialiasing");

	Params::MainMenuHUD_C_get_antialiasing Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MainMenuHUD.MainMenuHUD_C.get framerate
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMainMenuHUD_C::get_framerate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "get framerate");

	Params::MainMenuHUD_C_get_framerate Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MainMenuHUD.MainMenuHUD_C.Get Resoluton
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMainMenuHUD_C::Get_Resoluton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "Get Resoluton");

	Params::MainMenuHUD_C_Get_Resoluton Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MainMenuHUD.MainMenuHUD_C.get shader quality
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMainMenuHUD_C::get_shader_quality()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "get shader quality");

	Params::MainMenuHUD_C_get_shader_quality Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MainMenuHUD.MainMenuHUD_C.Get shadow qual
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMainMenuHUD_C::Get_shadow_qual()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "Get shadow qual");

	Params::MainMenuHUD_C_Get_shadow_qual Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MainMenuHUD.MainMenuHUD_C.Get texturre quality
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMainMenuHUD_C::Get_texturre_quality()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "Get texturre quality");

	Params::MainMenuHUD_C_Get_texturre_quality Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MainMenuHUD.MainMenuHUD_C.get vsync
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMainMenuHUD_C::get_vsync()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "get vsync");

	Params::MainMenuHUD_C_get_vsync Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MainMenuHUD.MainMenuHUD_C.Get window mode
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UMainMenuHUD_C::Get_window_mode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "Get window mode");

	Params::MainMenuHUD_C_Get_window_mode Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MainMenuHUD.MainMenuHUD_C.On start
// (BlueprintCallable, BlueprintEvent)

void UMainMenuHUD_C::On_start()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "On start");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.OpenSettings
// (BlueprintCallable, BlueprintEvent)

void UMainMenuHUD_C::OpenSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "OpenSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainMenuHUD.MainMenuHUD_C.Set ALL
// (BlueprintCallable, BlueprintEvent)

void UMainMenuHUD_C::Set_ALL()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainMenuHUD_C", "Set ALL");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
