#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MENU

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass MENU.MENU_C
// 0x0008 (0x02B8 - 0x02B0)
class AMENU_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_MENU(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MENU_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MENU_C")
	}
	static class AMENU_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMENU_C>();
	}
};
DUMPER7_ASSERTS_AMENU_C;

SDK_NAMESPACE_END
