#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OdpadkoveKose

#include "Basic.hpp"

#include "E_Difficulty_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass OdpadkoveKose.OdpadkoveKose_C
// 0x00A8 (0x0350 - 0x02A8)
class AOdpadkoveKose_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPaperSpriteComponent*                  PaperSprite;                                       // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UWidgetComponent*                       Widget;                                            // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_NewTrack_0_D772F7A8405530F91832F79BA568D544; // 0x02D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline__Direction_D772F7A8405530F91832F79BA568D544; // 0x02D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D5[0x3];                                      // 0x02D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline;                                          // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class ABP_FirstPersonCharacter_C*             Hrac;                                              // 0x02E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        Kolko_treba_drzat;                                 // 0x02E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Hodnota;                                           // 0x02F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        kolko_vazim;                                       // 0x02F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                start_loc;                                         // 0x0300(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Empty;                                             // 0x0318(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_319[0x7];                                      // 0x0319(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        MaxMaxWin;                                         // 0x0320(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Is_Locked_;                                        // 0x0328(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_Difficulty                                  LockPickDifficulty;                                // 0x0329(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_32A[0x2];                                      // 0x032A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Aky_Kontajner_vybrat;                              // 0x032C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	double                                        Kolko_Drzim;                                       // 0x0330(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWB_RoundProgressBar_C*                 SELF_WB_Round_Progress_Bar;                        // 0x0338(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Unlocking;                                         // 0x0340(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Popup_;                                            // 0x0341(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_342[0x2];                                      // 0x0342(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Id_kontajneru;                                     // 0x0344(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SomLockedArea_;                                    // 0x0348(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void Adrenaline_(int32 Amount___Max_3);
	void ExecuteUbergraph_OdpadkoveKose(int32 EntryPoint);
	void find_look_at();
	void InterakciaHold(double Kolko_Drzim_0);
	void Interakica();
	void Kolko_je_spawned_smeti_(int32* Kolko_, int32* Kolko_je_max_);
	void KukamNaTeba(bool NE);
	void LockPick();
	void OnGameLoad();
	void PosliHodnotuLootu(double Váha_kg, double Hodnota_0);
	void random_value_zase();
	void ReceiveBeginPlay();
	void Refka_na_Progressbar(class UWB_RoundProgressBar_C** PB);
	void RemoveDynamicEventTxt();
	void ResetKolkoDrzim();
	void ResumeTimer();
	void SetStaticMesh();
	void Spawnol_som_smeti();
	void Stop_timerEvent();
	void Timeline__FinishedFunc();
	void Timeline__UpdateFunc();
	void Ukončil_som_Pickup_Predčasne();
	bool Unesiem_to_();
	void UnlockLockPick();
	void UserConstructionScript();
	void ZiskajHraca(class ABP_FirstPersonCharacter_C** Hrac_0);
	void Zobral_som_odpadok();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("OdpadkoveKose_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OdpadkoveKose_C")
	}
	static class AOdpadkoveKose_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOdpadkoveKose_C>();
	}
};
DUMPER7_ASSERTS_AOdpadkoveKose_C;

SDK_NAMESPACE_END
