#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PawelTrader

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PawelTrader.PawelTrader_C
// 0x0070 (0x06C0 - 0x0650)
class APawelTrader_C final : public ACharacter
{
public:
	uint8                                         Pad_648[0x8];                                      // 0x0648(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0650(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPaperSpriteComponent*                  PaperSprite;                                       // 0x0658(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UTextRenderComponent*                   TextRender;                                        // 0x0660(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_NewTrack_0_60214162428A6A71A8238AB2E9A111AF; // 0x0668(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline__Direction_60214162428A6A71A8238AB2E9A111AF; // 0x066C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_66D[0x3];                                      // 0x066D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline;                                          // 0x0670(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class ABP_FirstPersonCharacter_C*             Hrac;                                              // 0x0678(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FVector                                start_loc;                                         // 0x0680(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Kolko_lootu_si_doniesol;                           // 0x0698(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_69C[0x4];                                      // 0x069C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              One_Sale;                                          // 0x06A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                         Koľko_si_dokopy_minu_u_pawla_no_reset;             // 0x06B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Adrenaline_(int32 Amount___Max_3);
	void ExecuteUbergraph_PawelTrader(int32 EntryPoint);
	void Finished_352AFA5749F98F91CEBD4489D72119FB();
	void Interakica();
	void Kolko_je_spawned_smeti_(int32* Kolko_, int32* Kolko_je_max_);
	void KukamNaTeba(bool NE);
	void lookat();
	void PosliHodnotuLootu(double Váha_kg, double Hodnota);
	void ReceiveBeginPlay();
	void Refka_na_Progressbar(class UWB_RoundProgressBar_C** PB);
	void RemoveDynamicEventTxt();
	void ResetKolkoDrzim();
	void ResumeTimer();
	void Spawnol_som_smeti();
	void Stop_timerEvent();
	void Timeline__FinishedFunc();
	void Timeline__UpdateFunc();
	void Ukončil_som_Pickup_Predčasne();
	void UnlockLockPick();
	void Zapocitaj_kolko_si_spendol();
	void ZiskajHraca(class ABP_FirstPersonCharacter_C** Hrac_0);
	void Zobral_som_odpadok();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PawelTrader_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PawelTrader_C")
	}
	static class APawelTrader_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APawelTrader_C>();
	}
};
DUMPER7_ASSERTS_APawelTrader_C;

SDK_NAMESPACE_END
