#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PickUpShake

#include "Basic.hpp"

#include "EngineCameras_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PickUpShake.PickUpShake_C
// 0x0000 (0x01F0 - 0x01F0)
class UPickUpShake_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PickUpShake_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PickUpShake_C")
	}
	static class UPickUpShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPickUpShake_C>();
	}
};
DUMPER7_ASSERTS_UPickUpShake_C;

SDK_NAMESPACE_END
