#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PickLockminigame

#include "Basic.hpp"

#include "PickLockminigame_classes.hpp"
#include "PickLockminigame_parameters.hpp"


SDK_NAMESPACE_START

// Function PickLockminigame.PickLockminigame_C.CloseLockPICK
// (BlueprintCallable, BlueprintEvent)

void APickLockminigame_C::CloseLockPICK()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "CloseLockPICK");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PickLockminigame.PickLockminigame_C.ExecuteUbergraph_PickLockminigame
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APickLockminigame_C::ExecuteUbergraph_PickLockminigame(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "ExecuteUbergraph_PickLockminigame");

	Params::PickLockminigame_C_ExecuteUbergraph_PickLockminigame Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickLockminigame.PickLockminigame_C.InpActEvt_IA_Jump_K2Node_EnhancedInputActionEvent_1
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void APickLockminigame_C::InpActEvt_IA_Jump_K2Node_EnhancedInputActionEvent_1(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "InpActEvt_IA_Jump_K2Node_EnhancedInputActionEvent_1");

	Params::PickLockminigame_C_InpActEvt_IA_Jump_K2Node_EnhancedInputActionEvent_1 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickLockminigame.PickLockminigame_C.InpActEvt_IA_Jump_K2Node_EnhancedInputActionEvent_2
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void APickLockminigame_C::InpActEvt_IA_Jump_K2Node_EnhancedInputActionEvent_2(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "InpActEvt_IA_Jump_K2Node_EnhancedInputActionEvent_2");

	Params::PickLockminigame_C_InpActEvt_IA_Jump_K2Node_EnhancedInputActionEvent_2 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickLockminigame.PickLockminigame_C.InpActEvt_IA_Jump_K2Node_EnhancedInputActionEvent_3
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void APickLockminigame_C::InpActEvt_IA_Jump_K2Node_EnhancedInputActionEvent_3(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "InpActEvt_IA_Jump_K2Node_EnhancedInputActionEvent_3");

	Params::PickLockminigame_C_InpActEvt_IA_Jump_K2Node_EnhancedInputActionEvent_3 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickLockminigame.PickLockminigame_C.InpActEvt_IA_TabESC_K2Node_EnhancedInputActionEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void APickLockminigame_C::InpActEvt_IA_TabESC_K2Node_EnhancedInputActionEvent_0(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "InpActEvt_IA_TabESC_K2Node_EnhancedInputActionEvent_0");

	Params::PickLockminigame_C_InpActEvt_IA_TabESC_K2Node_EnhancedInputActionEvent_0 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickLockminigame.PickLockminigame_C.PassPickSound
// (BlueprintCallable, BlueprintEvent)

void APickLockminigame_C::PassPickSound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "PassPickSound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PickLockminigame.PickLockminigame_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void APickLockminigame_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PickLockminigame.PickLockminigame_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APickLockminigame_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "ReceiveTick");

	Params::PickLockminigame_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickLockminigame.PickLockminigame_C.ResetDoOnceRotation
// (BlueprintCallable, BlueprintEvent)

void APickLockminigame_C::ResetDoOnceRotation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "ResetDoOnceRotation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PickLockminigame.PickLockminigame_C.Set difficulty
// (BlueprintCallable, BlueprintEvent)

void APickLockminigame_C::Set_difficulty()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "Set difficulty");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PickLockminigame.PickLockminigame_C.Set Rotation
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  elapsed_sec                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APickLockminigame_C::Set_Rotation(double elapsed_sec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "Set Rotation");

	Params::PickLockminigame_C_Set_Rotation Parms{};

	Parms.elapsed_sec = elapsed_sec;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PickLockminigame.PickLockminigame_C.Set Win Number
// (BlueprintCallable, BlueprintEvent)

void APickLockminigame_C::Set_Win_Number()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "Set Win Number");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PickLockminigame.PickLockminigame_C.Timeline__FinishedFunc
// (BlueprintEvent)

void APickLockminigame_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PickLockminigame.PickLockminigame_C.Timeline__UpdateFunc
// (BlueprintEvent)

void APickLockminigame_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PickLockminigame_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
