#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Plagát

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Plagát.Plagát_C
// 0x0018 (0x02C0 - 0x02A8)
class APlagát_C final : public AActor
{
public:
	class UPaperSpriteComponent*                  PaperSprite;                                       // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         Aký_;                                              // 0x02B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Plagát_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Plagát_C")
	}
	static class APlagát_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APlagát_C>();
	}
};
DUMPER7_ASSERTS_APlagát_C;

SDK_NAMESPACE_END
