#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomTimeAmbientPlayer

#include "Basic.hpp"

#include "RandomTimeAmbientPlayer_classes.hpp"
#include "RandomTimeAmbientPlayer_parameters.hpp"


SDK_NAMESPACE_START

// Function RandomTimeAmbientPlayer.RandomTimeAmbientPlayer_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ARandomTimeAmbientPlayer_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomTimeAmbientPlayer_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomTimeAmbientPlayer.RandomTimeAmbientPlayer_C.ExecuteUbergraph_RandomTimeAmbientPlayer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ARandomTimeAmbientPlayer_C::ExecuteUbergraph_RandomTimeAmbientPlayer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RandomTimeAmbientPlayer_C", "ExecuteUbergraph_RandomTimeAmbientPlayer");

	Params::RandomTimeAmbientPlayer_C_ExecuteUbergraph_RandomTimeAmbientPlayer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
