#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_LockedAreas

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct S_LockedAreas.S_LockedAreas
// 0x0002 (0x0002 - 0x0000)
struct FS_LockedAreas final
{
public:
	bool                                          Cooldown_3_695CA88247D0C86412E146B042CE4D7B;       // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          PlayerInside_4_8284452A4FB7B17B2CEBC8803DC3AA5E;   // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FS_LockedAreas;

SDK_NAMESPACE_END
