#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_SaveKontajner

#include "Basic.hpp"

#include "E_Difficulty_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct S_SaveKontajner.S_SaveKontajner
// 0x0020 (0x0020 - 0x0000)
struct FS_SaveKontajner final
{
public:
	double                                        Kolkotrebadrzat_2_C2F564B843B010CE541942B09196593E; // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Hodnota_5_7B35377B4B585DAB28235489D4FC1115;        // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Kolkovazim_7_B25006C94AE2EA98A8A9DAB71045D47D;     // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Empty__10_11A90CBD433A65ADAD2E73894F57040D;        // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Locked__12_7DAC740E448611B6B5FBF4BD94F92C82;       // 0x0019(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_Difficulty                                  Difficulty_15_4BC2F48343C0FEFC88A5E4AAF827AB2B;    // 0x001A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FS_SaveKontajner;

SDK_NAMESPACE_END
