#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShadyMiro

#include "Basic.hpp"

#include "ShadyMiro_classes.hpp"
#include "ShadyMiro_parameters.hpp"


SDK_NAMESPACE_START

// Function ShadyMiro.ShadyMiro_C.Zobral som odpadok
// (Public, BlueprintCallable, BlueprintEvent)

void AShadyMiro_C::Zobral_som_odpadok()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "Zobral som odpadok");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShadyMiro.ShadyMiro_C.ZiskajHraca
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_FirstPersonCharacter_C**      Hrac                                                   (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AShadyMiro_C::ZiskajHraca(class ABP_FirstPersonCharacter_C** Hrac)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "ZiskajHraca");

	Params::ShadyMiro_C_ZiskajHraca Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Hrac != nullptr)
		*Hrac = Parms.Hrac;
}


// Function ShadyMiro.ShadyMiro_C.UnlockLockPick
// (Public, BlueprintCallable, BlueprintEvent)

void AShadyMiro_C::UnlockLockPick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "UnlockLockPick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShadyMiro.ShadyMiro_C.Ukončil som Pickup Predčasne
// (Public, BlueprintCallable, BlueprintEvent)

void AShadyMiro_C::Ukončil_som_Pickup_Predčasne()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "Ukončil som Pickup Predčasne");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShadyMiro.ShadyMiro_C.Timeline__UpdateFunc
// (BlueprintEvent)

void AShadyMiro_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShadyMiro.ShadyMiro_C.Timeline__FinishedFunc
// (BlueprintEvent)

void AShadyMiro_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShadyMiro.ShadyMiro_C.Stop timerEvent
// (Public, BlueprintCallable, BlueprintEvent)

void AShadyMiro_C::Stop_timerEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "Stop timerEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShadyMiro.ShadyMiro_C.Spawnol som smeti
// (Public, BlueprintCallable, BlueprintEvent)

void AShadyMiro_C::Spawnol_som_smeti()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "Spawnol som smeti");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShadyMiro.ShadyMiro_C.ResumeTimer
// (Public, BlueprintCallable, BlueprintEvent)

void AShadyMiro_C::ResumeTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "ResumeTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShadyMiro.ShadyMiro_C.ResetKolkoDrzim
// (Public, BlueprintCallable, BlueprintEvent)

void AShadyMiro_C::ResetKolkoDrzim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "ResetKolkoDrzim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShadyMiro.ShadyMiro_C.RemoveDynamicEventTxt
// (Public, BlueprintCallable, BlueprintEvent)

void AShadyMiro_C::RemoveDynamicEventTxt()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "RemoveDynamicEventTxt");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShadyMiro.ShadyMiro_C.Refka na Progressbar
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWB_RoundProgressBar_C**          PB                                                     (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void AShadyMiro_C::Refka_na_Progressbar(class UWB_RoundProgressBar_C** PB)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "Refka na Progressbar");

	Params::ShadyMiro_C_Refka_na_Progressbar Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PB != nullptr)
		*PB = Parms.PB;
}


// Function ShadyMiro.ShadyMiro_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AShadyMiro_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShadyMiro.ShadyMiro_C.PosliHodnotuLootu
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Váha_kg                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Hodnota                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AShadyMiro_C::PosliHodnotuLootu(double Váha_kg, double Hodnota)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "PosliHodnotuLootu");

	Params::ShadyMiro_C_PosliHodnotuLootu Parms{};

	Parms.Váha_kg = Váha_kg;
	Parms.Hodnota = Hodnota;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ShadyMiro.ShadyMiro_C.lookat
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AShadyMiro_C::lookat()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "lookat");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShadyMiro.ShadyMiro_C.KukamNaTeba
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NE                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AShadyMiro_C::KukamNaTeba(bool NE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "KukamNaTeba");

	Params::ShadyMiro_C_KukamNaTeba Parms{};

	Parms.NE = NE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ShadyMiro.ShadyMiro_C.Kolko je spawned smeti?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32*                                  Kolko_                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Kolko_je_max_                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AShadyMiro_C::Kolko_je_spawned_smeti_(int32* Kolko_, int32* Kolko_je_max_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "Kolko je spawned smeti?");

	Params::ShadyMiro_C_Kolko_je_spawned_smeti_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Kolko_ != nullptr)
		*Kolko_ = Parms.Kolko_;

	if (Kolko_je_max_ != nullptr)
		*Kolko_je_max_ = Parms.Kolko_je_max_;
}


// Function ShadyMiro.ShadyMiro_C.Interakica
// (Public, BlueprintCallable, BlueprintEvent)

void AShadyMiro_C::Interakica()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "Interakica");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShadyMiro.ShadyMiro_C.ExecuteUbergraph_ShadyMiro
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AShadyMiro_C::ExecuteUbergraph_ShadyMiro(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "ExecuteUbergraph_ShadyMiro");

	Params::ShadyMiro_C_ExecuteUbergraph_ShadyMiro Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ShadyMiro.ShadyMiro_C.Adrenaline+
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Amount___Max_3                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AShadyMiro_C::Adrenaline_(int32 Amount___Max_3)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ShadyMiro_C", "Adrenaline+");

	Params::ShadyMiro_C_Adrenaline_ Parms{};

	Parms.Amount___Max_3 = Amount___Max_3;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
