#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Transient

#include "Basic.hpp"

#include "PBIK_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "ControlRig_structs.hpp"
#include "RigVM_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// PropertyBag Transient.PropertyBag_53d3db1cc7cc37cb
// 0x04E0 (0x04E0 - 0x0000)
struct FPropertyBag_53d3db1cc7cc37cb final
{
public:
	struct FVector                                RigVMModel___FootTrace_Hit_Location;               // 0x0000(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                FootTrace___FootTrace_MathVectorAdd_Result;        // 0x0018(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             FootTrace___FootTrace_GetTransform_Transform;      // 0x0030(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCachedRigElement>              FootTrace___FootTrace_GetTransform_CachedIndex;    // 0x0090(0x0010)(Edit)
	struct FVector                                FootTrace___FootTrace_MathVectorAdd_A__IO;         // 0x00A0(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FootTrace___FootTrace_MathFloatAdd_Result;         // 0x00B8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FootTrace___FootTrace_MathFloatAdd_A;              // 0x00BC(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             FootTrace___FootTrace_GetTransform_1_Transform;    // 0x00C0(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCachedRigElement>              FootTrace___FootTrace_GetTransform_1_CachedIndex;  // 0x0120(0x0010)(Edit)
	struct FVector                                FootTrace___FootTrace_MathVectorSub_Result;        // 0x0130(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                FootTrace___FootTrace_MathVectorSub_A__IO;         // 0x0148(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          FootTrace___FootTrace_SphereTraceByTraceChannel_1_bHit; // 0x0160(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_161[0x7];                                      // 0x0161(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                FootTrace___FootTrace_SphereTraceByTraceChannel_1_HitNormal; // 0x0168(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FRigUnit_SphereTrace_WorkData>  FootTrace___FootTrace_SphereTraceByTraceChannel_1_WorkData; // 0x0180(0x0010)(Edit)
	struct FVector                                RigVMModel___FootTrace_1_Hit_Location;             // 0x0190(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                FootTrace_1___FootTrace_MathVectorAdd_Result;      // 0x01A8(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             FootTrace_1___FootTrace_GetTransform_Transform;    // 0x01C0(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCachedRigElement>              FootTrace_1___FootTrace_GetTransform_CachedIndex;  // 0x0220(0x0010)(Edit)
	struct FVector                                FootTrace_1___FootTrace_MathVectorAdd_A__IO;       // 0x0230(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FootTrace_1___FootTrace_MathFloatAdd_Result;       // 0x0248(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FootTrace_1___FootTrace_MathFloatAdd_A;            // 0x024C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             FootTrace_1___FootTrace_GetTransform_1_Transform;  // 0x0250(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCachedRigElement>              FootTrace_1___FootTrace_GetTransform_1_CachedIndex; // 0x02B0(0x0010)(Edit)
	struct FVector                                FootTrace_1___FootTrace_MathVectorSub_Result;      // 0x02C0(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                FootTrace_1___FootTrace_MathVectorSub_A__IO;       // 0x02D8(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          FootTrace_1___FootTrace_SphereTraceByTraceChannel_1_bHit; // 0x02F0(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F1[0x7];                                      // 0x02F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                FootTrace_1___FootTrace_SphereTraceByTraceChannel_1_HitNormal; // 0x02F8(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FRigUnit_SphereTrace_WorkData>  FootTrace_1___FootTrace_SphereTraceByTraceChannel_1_WorkData; // 0x0310(0x0010)(Edit)
	class FName                                   RigVMModel___Branch_RigVMUnitNode_BlockToRun;      // 0x0320(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RigVMModel___AlphaInterp_Result;                   // 0x0328(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RigVMModel___AlphaInterp_Value;                    // 0x032C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FInputScaleBiasClamp>           RigVMModel___AlphaInterp_ScaleBiasClamp;           // 0x0330(0x0010)(Edit)
	float                                         RigVMModel___AlphaInterp_1_Result;                 // 0x0340(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RigVMModel___AlphaInterp_1_Value;                  // 0x0344(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FInputScaleBiasClamp>           RigVMModel___AlphaInterp_1_ScaleBiasClamp;         // 0x0348(0x0010)(Edit)
	double                                        RigVMModel___If_DISPATCH_RigVMDispatch_If_Result;  // 0x0358(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          RigVMModel___MathFloatLess_Result;                 // 0x0360(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_361[0x3];                                      // 0x0361(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         RigVMModel___MathFloatLess_A;                      // 0x0364(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RigVMModel___MathFloatLess_B;                      // 0x0368(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          RigVMModel___If_DISPATCH_RigVMDispatch_If_Condition; // 0x036C(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_36D[0x3];                                      // 0x036D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FRigUnit_ModifyTransforms_PerItem> RigVMModel___ModifyTransforms_ItemToModify__IO; // 0x0370(0x0010)(Edit)
	TArray<struct FRigUnit_ModifyTransforms_WorkData> RigVMModel___ModifyTransforms_WorkData;        // 0x0380(0x0010)(Edit)
	TArray<struct FRigUnit_ModifyTransforms_PerItem> RigVMModel___ModifyTransforms_1_ItemToModify__IO; // 0x0390(0x0010)(Edit)
	TArray<struct FRigUnit_ModifyTransforms_WorkData> RigVMModel___ModifyTransforms_1_WorkData;      // 0x03A0(0x0010)(Edit)
	TArray<struct FRigUnit_ModifyTransforms_PerItem> RigVMModel___ModifyTransforms_1_1_ItemToModify__IO; // 0x03B0(0x0010)(Edit)
	TArray<struct FRigUnit_ModifyTransforms_WorkData> RigVMModel___ModifyTransforms_1_1_WorkData;    // 0x03C0(0x0010)(Edit)
	TArray<struct FPBIKEffector>                  RigVMModel___PBIK_Effectors__IO;                   // 0x03D0(0x0010)(Edit)
	struct FTransform                             RigVMModel___GetTransform_Transform;               // 0x03E0(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCachedRigElement>              RigVMModel___GetTransform_CachedIndex;             // 0x0440(0x0010)(Edit)
	struct FTransform                             RigVMModel___GetTransform_1_Transform;             // 0x0450(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCachedRigElement>              RigVMModel___GetTransform_1_CachedIndex;           // 0x04B0(0x0010)(Edit)
	TArray<TArray<int32>>                         RigVMModel___PBIK_EffectorSolverIndices;           // 0x04C0(0x0010)(Edit)
	TArray<struct FPBIKWorkData>                  RigVMModel___PBIK_WorkData;                        // 0x04D0(0x0010)(Edit)
};
DUMPER7_ASSERTS_FPropertyBag_53d3db1cc7cc37cb;

// ScriptStruct Transient.ChaosDestructionEvent_SWC
// 0x0044 (0x0044 - 0x0000)
struct FChaosDestructionEvent_SWC final
{
public:
	struct FVector3f                              position;                                          // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector3f                              Normal;                                            // 0x000C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector3f                              Velocity;                                          // 0x0018(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector3f                              AngularVelocity;                                   // 0x0024(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ExtentMin;                                         // 0x0030(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ExtentMax;                                         // 0x0034(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ParticleID;                                        // 0x0038(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Time;                                              // 0x003C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Type;                                              // 0x0040(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FChaosDestructionEvent_SWC;

// PropertyBag Transient.PropertyBag_39394335280063d8
// 0x0148 (0x0148 - 0x0000)
struct FPropertyBag_39394335280063d8 final
{
public:
	struct FRigElementKey                         RigVMModel___FootTrace_Item__Const;                // 0x0000(0x000C)(Edit, NoDestructor, HasGetValueTypeHash)
	ERigVMTransformSpace                          FootTrace___FootTrace_GetTransform_Space__Const;   // 0x000C(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          FootTrace___FootTrace_GetTransform_bInitial__Const; // 0x000D(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         FootTrace___FootTrace_MathFloatAdd_B__Const;       // 0x0010(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRigElementKey                         FootTrace___FootTrace_GetTransform_1_Item__Const;  // 0x0014(0x000C)(Edit, NoDestructor, HasGetValueTypeHash)
	struct FVector                                FootTrace___FootTrace_MathVectorAdd_B__Const;      // 0x0020(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                FootTrace___FootTrace_MathVectorSub_B__Const;      // 0x0038(0x0018)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETraceTypeQuery                               FootTrace___FootTrace_SphereTraceByTraceChannel_1_TraceChannel__Const; // 0x0050(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRigElementKey                         RigVMModel___FootTrace_1_Item__Const;              // 0x0054(0x000C)(Edit, NoDestructor, HasGetValueTypeHash)
	double                                        RigVMModel___VariableNode_9_Value__Const;          // 0x0060(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RigVMModel___AlphaInterp_Scale__Const;             // 0x0068(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RigVMModel___AlphaInterp_Bias__Const;              // 0x006C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          RigVMModel___AlphaInterp_bMapRange__Const;         // 0x0070(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71[0x3];                                       // 0x0071(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputRange                            RigVMModel___AlphaInterp_InRange__Const;           // 0x0074(0x0008)(Edit, NoDestructor)
	bool                                          RigVMModel___AlphaInterp_bInterpResult__Const;     // 0x007C(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7D[0x3];                                       // 0x007D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         RigVMModel___AlphaInterp_InterpSpeedIncreasing__Const; // 0x0080(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_84[0x4];                                       // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FRigUnit_ModifyTransforms_PerItem> RigVMModel___ModifyTransforms_ItemToModify__Const; // 0x0088(0x0010)(Edit)
	EControlRigModifyBoneMode                     RigVMModel___ModifyTransforms_Mode__Const;         // 0x0098(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_99[0x7];                                       // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FRigUnit_ModifyTransforms_PerItem> RigVMModel___ModifyTransforms_1_ItemToModify__Const; // 0x00A0(0x0010)(Edit)
	TArray<struct FRigUnit_ModifyTransforms_PerItem> RigVMModel___ModifyTransforms_1_1_ItemToModify__Const; // 0x00B0(0x0010)(Edit)
	class FName                                   RigVMModel___PBIK_Root__Const;                     // 0x00C0(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FPBIKEffector>                  RigVMModel___PBIK_Effectors__Const;                // 0x00C8(0x0010)(Edit)
	ERigVMTransformSpace                          RigVMModel___GetTransform_Space__Const;            // 0x00D8(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FPBIKBoneSetting>               RigVMModel___PBIK_BoneSettings__Const;             // 0x00E0(0x0010)(Edit)
	TArray<class FName>                           RigVMModel___PBIK_ExcludedBones__Const;            // 0x00F0(0x0010)(Edit)
	struct FPBIKSolverSettings                    RigVMModel___PBIK_Settings__Const;                 // 0x0100(0x0040)(Edit, NoDestructor)
	struct FPBIKDebug                             RigVMModel___PBIK_Debug__Const;                    // 0x0140(0x0008)(Edit, NoDestructor)
};
DUMPER7_ASSERTS_FPropertyBag_39394335280063d8;

// PropertyBag Transient.PropertyBag_f992f01d472ba4be
// 0x0078 (0x0078 - 0x0000)
struct FPropertyBag_f992f01d472ba4be final
{
public:
	TArray<struct FRigElementKey>                 RigVMModel___FABRIKItemArray_Items__Const;         // 0x0000(0x0010)(Edit)
	struct FRigElementKey                         RigVMModel___RigUnit_GetTransform_4_Item__Const;   // 0x0010(0x000C)(Edit, NoDestructor, HasGetValueTypeHash)
	ERigVMTransformSpace                          RigVMModel___RigUnit_GetTransform_4_Space__Const;  // 0x001C(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          RigVMModel___RigUnit_GetTransform_4_bInitial__Const; // 0x001D(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E[0x2];                                       // 0x001E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         RigVMModel___FABRIKItemArray_Precision__Const;     // 0x0020(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RigVMModel___FABRIKItemArray_Weight__Const;        // 0x0024(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          RigVMModel___FABRIKItemArray_bPropagateToChildren__Const; // 0x0028(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         RigVMModel___FABRIKItemArray_MaxIterations__Const; // 0x002C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRigElementKey                         RigVMModel___Set_Transform_Item__Const;            // 0x0030(0x000C)(Edit, NoDestructor, HasGetValueTypeHash)
	struct FRigElementKey                         RigVMModel___RigUnit_GetTransform_2_Item__Const;   // 0x003C(0x000C)(Edit, NoDestructor, HasGetValueTypeHash)
	struct FRigElementKey                         RigVMModel___Set_Transform_1_Item__Const;          // 0x0048(0x000C)(Edit, NoDestructor, HasGetValueTypeHash)
	struct FRigElementKey                         RigVMModel___RigUnit_GetTransform_3_Item__Const;   // 0x0054(0x000C)(Edit, NoDestructor, HasGetValueTypeHash)
	struct FRigElementKey                         RigVMModel___Set_Transform_2_Item__Const;          // 0x0060(0x000C)(Edit, NoDestructor, HasGetValueTypeHash)
	struct FRigElementKey                         RigVMModel___RigUnit_GetTransform_5_Item__Const;   // 0x006C(0x000C)(Edit, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FPropertyBag_f992f01d472ba4be;

// PropertyBag Transient.PropertyBag_2b4a7ae12d20eb77
// 0x03A0 (0x03A0 - 0x0000)
struct FPropertyBag_2b4a7ae12d20eb77 final
{
public:
	struct FTransform                             RigVMModel___RigUnit_GetTransform_4_Transform;     // 0x0000(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCachedRigElement>              RigVMModel___RigUnit_GetTransform_4_CachedIndex;   // 0x0060(0x0010)(Edit)
	TArray<struct FRigUnit_FABRIK_WorkData>       RigVMModel___FABRIKItemArray_WorkData;             // 0x0070(0x0010)(Edit)
	struct FTransform                             RigVMModel___RigUnit_GetTransform_2_Transform;     // 0x0080(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCachedRigElement>              RigVMModel___RigUnit_GetTransform_2_CachedIndex;   // 0x00E0(0x0010)(Edit)
	TArray<struct FCachedRigElement>              RigVMModel___Set_Transform_CachedIndex;            // 0x00F0(0x0010)(Edit)
	struct FTransform                             RigVMModel___GetTransform_Transform;               // 0x0100(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCachedRigElement>              RigVMModel___GetTransform_CachedIndex;             // 0x0160(0x0010)(Edit)
	struct FTransform                             RigVMModel___Set_Transform_1_Value__IO;            // 0x0170(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             RigVMModel___RigUnit_GetTransform_3_Transform;     // 0x01D0(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCachedRigElement>              RigVMModel___RigUnit_GetTransform_3_CachedIndex;   // 0x0230(0x0010)(Edit)
	TArray<struct FCachedRigElement>              RigVMModel___Set_Transform_1_CachedIndex;          // 0x0240(0x0010)(Edit)
	struct FTransform                             RigVMModel___GetTransform_1_Transform;             // 0x0250(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCachedRigElement>              RigVMModel___GetTransform_1_CachedIndex;           // 0x02B0(0x0010)(Edit)
	struct FTransform                             RigVMModel___Set_Transform_2_Value__IO;            // 0x02C0(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             RigVMModel___RigUnit_GetTransform_5_Transform;     // 0x0320(0x0060)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FCachedRigElement>              RigVMModel___RigUnit_GetTransform_5_CachedIndex;   // 0x0380(0x0010)(Edit)
	TArray<struct FCachedRigElement>              RigVMModel___Set_Transform_2_CachedIndex;          // 0x0390(0x0010)(Edit)
};
DUMPER7_ASSERTS_FPropertyBag_2b4a7ae12d20eb77;

SDK_NAMESPACE_END
