#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TrashSpawner

#include "Basic.hpp"

#include "TrashSpawner_classes.hpp"
#include "TrashSpawner_parameters.hpp"


SDK_NAMESPACE_START

// Function TrashSpawner.TrashSpawner_C.Zobral som odpadok
// (Public, BlueprintCallable, BlueprintEvent)

void ATrashSpawner_C::Zobral_som_odpadok()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "Zobral som odpadok");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TrashSpawner.TrashSpawner_C.ZiskajHraca
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_FirstPersonCharacter_C**      Hrac                                                   (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ATrashSpawner_C::ZiskajHraca(class ABP_FirstPersonCharacter_C** Hrac)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "ZiskajHraca");

	Params::TrashSpawner_C_ZiskajHraca Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Hrac != nullptr)
		*Hrac = Parms.Hrac;
}


// Function TrashSpawner.TrashSpawner_C.UnlockLockPick
// (Public, BlueprintCallable, BlueprintEvent)

void ATrashSpawner_C::UnlockLockPick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "UnlockLockPick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TrashSpawner.TrashSpawner_C.Ukončil som Pickup Predčasne
// (Public, BlueprintCallable, BlueprintEvent)

void ATrashSpawner_C::Ukončil_som_Pickup_Predčasne()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "Ukončil som Pickup Predčasne");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TrashSpawner.TrashSpawner_C.Stop timerEvent
// (Public, BlueprintCallable, BlueprintEvent)

void ATrashSpawner_C::Stop_timerEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "Stop timerEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TrashSpawner.TrashSpawner_C.Spawnuj vo mne odpadok
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   LastIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATrashSpawner_C::Spawnuj_vo_mne_odpadok(int32 LastIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "Spawnuj vo mne odpadok");

	Params::TrashSpawner_C_Spawnuj_vo_mne_odpadok Parms{};

	Parms.LastIndex = LastIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TrashSpawner.TrashSpawner_C.Spawnol som smeti
// (Public, BlueprintCallable, BlueprintEvent)

void ATrashSpawner_C::Spawnol_som_smeti()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "Spawnol som smeti");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TrashSpawner.TrashSpawner_C.Spawn
// (BlueprintCallable, BlueprintEvent)

void ATrashSpawner_C::Spawn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "Spawn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TrashSpawner.TrashSpawner_C.ResumeTimer
// (Public, BlueprintCallable, BlueprintEvent)

void ATrashSpawner_C::ResumeTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "ResumeTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TrashSpawner.TrashSpawner_C.ResetKolkoDrzim
// (Public, BlueprintCallable, BlueprintEvent)

void ATrashSpawner_C::ResetKolkoDrzim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "ResetKolkoDrzim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TrashSpawner.TrashSpawner_C.RemoveDynamicEventTxt
// (Public, BlueprintCallable, BlueprintEvent)

void ATrashSpawner_C::RemoveDynamicEventTxt()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "RemoveDynamicEventTxt");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TrashSpawner.TrashSpawner_C.Refka na Progressbar
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWB_RoundProgressBar_C**          PB                                                     (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ATrashSpawner_C::Refka_na_Progressbar(class UWB_RoundProgressBar_C** PB)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "Refka na Progressbar");

	Params::TrashSpawner_C_Refka_na_Progressbar Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PB != nullptr)
		*PB = Parms.PB;
}


// Function TrashSpawner.TrashSpawner_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds_ReceiveTick                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATrashSpawner_C::ReceiveTick(float DeltaSeconds_ReceiveTick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "ReceiveTick");

	Params::TrashSpawner_C_ReceiveTick Parms{};

	Parms.DeltaSeconds_ReceiveTick = DeltaSeconds_ReceiveTick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TrashSpawner.TrashSpawner_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ATrashSpawner_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TrashSpawner.TrashSpawner_C.PosliHodnotuLootu
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Váha_kg                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Hodnota                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATrashSpawner_C::PosliHodnotuLootu(double Váha_kg, double Hodnota)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "PosliHodnotuLootu");

	Params::TrashSpawner_C_PosliHodnotuLootu Parms{};

	Parms.Váha_kg = Váha_kg;
	Parms.Hodnota = Hodnota;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TrashSpawner.TrashSpawner_C.KukamNaTeba
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NE                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATrashSpawner_C::KukamNaTeba(bool NE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "KukamNaTeba");

	Params::TrashSpawner_C_KukamNaTeba Parms{};

	Parms.NE = NE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TrashSpawner.TrashSpawner_C.Kolko je spawned smeti?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32*                                  Kolko_                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Kolko_je_max_                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATrashSpawner_C::Kolko_je_spawned_smeti_(int32* Kolko_, int32* Kolko_je_max_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "Kolko je spawned smeti?");

	Params::TrashSpawner_C_Kolko_je_spawned_smeti_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Kolko_ != nullptr)
		*Kolko_ = Parms.Kolko_;

	if (Kolko_je_max_ != nullptr)
		*Kolko_je_max_ = Parms.Kolko_je_max_;
}


// Function TrashSpawner.TrashSpawner_C.Interakica
// (Public, BlueprintCallable, BlueprintEvent)

void ATrashSpawner_C::Interakica()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "Interakica");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TrashSpawner.TrashSpawner_C.ExecuteUbergraph_TrashSpawner
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATrashSpawner_C::ExecuteUbergraph_TrashSpawner(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "ExecuteUbergraph_TrashSpawner");

	Params::TrashSpawner_C_ExecuteUbergraph_TrashSpawner Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TrashSpawner.TrashSpawner_C.Adrenaline+
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Amount___Max_3                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATrashSpawner_C::Adrenaline_(int32 Amount___Max_3)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TrashSpawner_C", "Adrenaline+");

	Params::TrashSpawner_C_Adrenaline_ Parms{};

	Parms.Amount___Max_3 = Amount___Max_3;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
