#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_TouchSimple

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UI_TouchSimple.UI_TouchSimple_C
// 0x0030 (0x0370 - 0x0340)
class UUI_TouchSimple_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUI_Thumbstick_C*                       Thumbstick_Move;                                   // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Thumbstick_C*                       Thumbstick_Aim;                                    // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Btn_Jump;                                          // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 In_String;                                         // 0x0360(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void BndEvt__UI_MobileOverlay_Btn_Jump_K2Node_ComponentBoundEvent_3_OnButtonPressedEvent__DelegateSignature();
	void BndEvt__UI_MobileOverlay_Thumbstick_Aim_K2Node_ComponentBoundEvent_2_Stick_Input__DelegateSignature(const struct FVector2D& NewParam);
	void BndEvt__UI_MobileOverlay_UI_Thumbstick_K2Node_ComponentBoundEvent_0_Stick_Input__DelegateSignature(const struct FVector2D& NewParam);
	void BndEvt__UI_TouchInterface_FirstPerson_Btn_Jump_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature();
	void Construct();
	void ExecuteUbergraph_UI_TouchSimple(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_TouchSimple_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_TouchSimple_C")
	}
	static class UUI_TouchSimple_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_TouchSimple_C>();
	}
};
DUMPER7_ASSERTS_UUI_TouchSimple_C;

SDK_NAMESPACE_END
