#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Thumbstick

#include "Basic.hpp"

#include "UI_Thumbstick_classes.hpp"
#include "UI_Thumbstick_parameters.hpp"


SDK_NAMESPACE_START

// Function UI_Thumbstick.UI_Thumbstick_C.Touch Input Check
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ETouchIndex                             FingerIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Thumbstick_C::Touch_Input_Check(ETouchIndex FingerIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Thumbstick_C", "Touch Input Check");

	Params::UI_Thumbstick_C_Touch_Input_Check Parms{};

	Parms.FingerIndex = FingerIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Thumbstick.UI_Thumbstick_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry_Tick                                        (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime_Tick                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Thumbstick_C::Tick(const struct FGeometry& MyGeometry_Tick, float InDeltaTime_Tick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Thumbstick_C", "Tick");

	Params::UI_Thumbstick_C_Tick Parms{};

	Parms.MyGeometry_Tick = std::move(MyGeometry_Tick);
	Parms.InDeltaTime_Tick = InDeltaTime_Tick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Thumbstick.UI_Thumbstick_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime_PreConstruct                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Thumbstick_C::PreConstruct(bool IsDesignTime_PreConstruct)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Thumbstick_C", "PreConstruct");

	Params::UI_Thumbstick_C_PreConstruct Parms{};

	Parms.IsDesignTime_PreConstruct = IsDesignTime_PreConstruct;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Thumbstick.UI_Thumbstick_C.ExecuteUbergraph_UI_Thumbstick
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Thumbstick_C::ExecuteUbergraph_UI_Thumbstick(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Thumbstick_C", "ExecuteUbergraph_UI_Thumbstick");

	Params::UI_Thumbstick_C_ExecuteUbergraph_UI_Thumbstick Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
