#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UpgradeMilan

#include "Basic.hpp"

#include "UpgradeMilan_classes.hpp"
#include "UpgradeMilan_parameters.hpp"


SDK_NAMESPACE_START

// Function UpgradeMilan.UpgradeMilan_C.Adrenaline+
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Amount___Max_3                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AUpgradeMilan_C::Adrenaline_(int32 Amount___Max_3)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "Adrenaline+");

	Params::UpgradeMilan_C_Adrenaline_ Parms{};

	Parms.Amount___Max_3 = Amount___Max_3;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UpgradeMilan.UpgradeMilan_C.CloseMenu
// (BlueprintCallable, BlueprintEvent)

void AUpgradeMilan_C::CloseMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "CloseMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.ExecuteUbergraph_UpgradeMilan
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AUpgradeMilan_C::ExecuteUbergraph_UpgradeMilan(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "ExecuteUbergraph_UpgradeMilan");

	Params::UpgradeMilan_C_ExecuteUbergraph_UpgradeMilan Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UpgradeMilan.UpgradeMilan_C.Interakica
// (Public, BlueprintCallable, BlueprintEvent)

void AUpgradeMilan_C::Interakica()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "Interakica");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.Kolko je spawned smeti?
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32*                                  Kolko_                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  Kolko_je_max_                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AUpgradeMilan_C::Kolko_je_spawned_smeti_(int32* Kolko_, int32* Kolko_je_max_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "Kolko je spawned smeti?");

	Params::UpgradeMilan_C_Kolko_je_spawned_smeti_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Kolko_ != nullptr)
		*Kolko_ = Parms.Kolko_;

	if (Kolko_je_max_ != nullptr)
		*Kolko_je_max_ = Parms.Kolko_je_max_;
}


// Function UpgradeMilan.UpgradeMilan_C.KukamNaTeba
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NE                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AUpgradeMilan_C::KukamNaTeba(bool NE)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "KukamNaTeba");

	Params::UpgradeMilan_C_KukamNaTeba Parms{};

	Parms.NE = NE;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UpgradeMilan.UpgradeMilan_C.lookat
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void AUpgradeMilan_C::lookat()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "lookat");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.OnAudioFinished_Event
// (BlueprintCallable, BlueprintEvent)

void AUpgradeMilan_C::OnAudioFinished_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "OnAudioFinished_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.PosliHodnotuLootu
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Váha_kg                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Hodnota                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AUpgradeMilan_C::PosliHodnotuLootu(double Váha_kg, double Hodnota)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "PosliHodnotuLootu");

	Params::UpgradeMilan_C_PosliHodnotuLootu Parms{};

	Parms.Váha_kg = Váha_kg;
	Parms.Hodnota = Hodnota;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UpgradeMilan.UpgradeMilan_C.RandomVoiceLine
// (BlueprintCallable, BlueprintEvent)

void AUpgradeMilan_C::RandomVoiceLine()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "RandomVoiceLine");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AUpgradeMilan_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.Refka na Progressbar
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWB_RoundProgressBar_C**          PB                                                     (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void AUpgradeMilan_C::Refka_na_Progressbar(class UWB_RoundProgressBar_C** PB)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "Refka na Progressbar");

	Params::UpgradeMilan_C_Refka_na_Progressbar Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PB != nullptr)
		*PB = Parms.PB;
}


// Function UpgradeMilan.UpgradeMilan_C.RemoveDynamicEventTxt
// (Public, BlueprintCallable, BlueprintEvent)

void AUpgradeMilan_C::RemoveDynamicEventTxt()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "RemoveDynamicEventTxt");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.ResetKolkoDrzim
// (Public, BlueprintCallable, BlueprintEvent)

void AUpgradeMilan_C::ResetKolkoDrzim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "ResetKolkoDrzim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.ResumeTimer
// (Public, BlueprintCallable, BlueprintEvent)

void AUpgradeMilan_C::ResumeTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "ResumeTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.Spawnol som smeti
// (Public, BlueprintCallable, BlueprintEvent)

void AUpgradeMilan_C::Spawnol_som_smeti()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "Spawnol som smeti");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.Stop timerEvent
// (Public, BlueprintCallable, BlueprintEvent)

void AUpgradeMilan_C::Stop_timerEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "Stop timerEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void AUpgradeMilan_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void AUpgradeMilan_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.Timeline_1__FinishedFunc
// (BlueprintEvent)

void AUpgradeMilan_C::Timeline_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "Timeline_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.Timeline_1__UpdateFunc
// (BlueprintEvent)

void AUpgradeMilan_C::Timeline_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "Timeline_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.Timeline__FinishedFunc
// (BlueprintEvent)

void AUpgradeMilan_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.Timeline__UpdateFunc
// (BlueprintEvent)

void AUpgradeMilan_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.Ukončil som Pickup Predčasne
// (Public, BlueprintCallable, BlueprintEvent)

void AUpgradeMilan_C::Ukončil_som_Pickup_Predčasne()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "Ukončil som Pickup Predčasne");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.UnlockLockPick
// (Public, BlueprintCallable, BlueprintEvent)

void AUpgradeMilan_C::UnlockLockPick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "UnlockLockPick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UpgradeMilan.UpgradeMilan_C.ZiskajHraca
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_FirstPersonCharacter_C**      Hrac_0                                                 (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AUpgradeMilan_C::ZiskajHraca(class ABP_FirstPersonCharacter_C** Hrac_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "ZiskajHraca");

	Params::UpgradeMilan_C_ZiskajHraca Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Hrac_0 != nullptr)
		*Hrac_0 = Parms.Hrac_0;
}


// Function UpgradeMilan.UpgradeMilan_C.Zobral som odpadok
// (Public, BlueprintCallable, BlueprintEvent)

void AUpgradeMilan_C::Zobral_som_odpadok()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeMilan_C", "Zobral som odpadok");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
