#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VipOdpadokEvent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass VipOdpadokEvent.VipOdpadokEvent_C
// 0x0090 (0x0338 - 0x02A8)
class AVipOdpadokEvent_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetComponent*                       Widget;                                            // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPaperSpriteComponent*                  PaperSprite;                                       // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM;                                                // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_NewTrack_0_3B8107E841302277D1759ABD1A60193D; // 0x02D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_0__Direction_3B8107E841302277D1759ABD1A60193D; // 0x02D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D5[0x3];                                      // 0x02D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_0;                                        // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_NewTrack_0_2E856E04458DA31ABC1ADC8F9DAEE8EA; // 0x02E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline__Direction_2E856E04458DA31ABC1ADC8F9DAEE8EA; // 0x02E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2E5[0x3];                                      // 0x02E5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline;                                          // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class ABP_FirstPersonCharacter_C*             Hrac;                                              // 0x02F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        Kolko_treba_drzat;                                 // 0x02F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Hodnota;                                           // 0x0300(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        kolko_vazim;                                       // 0x0308(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                start_loc;                                         // 0x0310(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWB_RoundProgressBar_C*                 SELF_WB_Round_Progress_Bar;                        // 0x0328(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        Kolko_Drzim;                                       // 0x0330(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Zobral_som_odpadok();
	void ZiskajHraca(class ABP_FirstPersonCharacter_C** Hrac);
	void UserConstructionScript();
	void UnlockLockPick();
	bool Unesiem_to_();
	void Ukončil_som_Pickup_Predčasne();
	void Timeline__UpdateFunc();
	void Timeline__FinishedFunc();
	void Timeline_0__UpdateFunc();
	void Timeline_0__FinishedFunc();
	void Stop_timerEvent();
	void Spawnol_som_smeti();
	void ResumeTimer();
	void ResetKolkoDrzim();
	void RemoveDynamicEventTxt();
	void Refka_na_Progressbar(class UWB_RoundProgressBar_C** PB);
	void ReceiveBeginPlay();
	void PosliHodnotuLootu(double Váha_kg, double Hodnota);
	void KukamNaTeba(bool NE);
	void Kolko_je_spawned_smeti_(int32* Kolko_, int32* Kolko_je_max_);
	void Interakica();
	void InterakciaHold(double Kolko_Drzim);
	void find_look_at();
	void ExecuteUbergraph_VipOdpadokEvent(int32 EntryPoint);
	void Adrenaline_(int32 Amount___Max_3);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("VipOdpadokEvent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VipOdpadokEvent_C")
	}
	static class AVipOdpadokEvent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVipOdpadokEvent_C>();
	}
};
DUMPER7_ASSERTS_AVipOdpadokEvent_C;

SDK_NAMESPACE_END
