#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_RoundProgressBar

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WB_RoundProgressBar.WB_RoundProgressBar_C
// 0x0040 (0x0380 - 0x0340)
class UWB_RoundProgressBar_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_32;                                          // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       Popoff;                                            // 0x0350(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       show;                                              // 0x0358(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               RoundedProgressBar;                                // 0x0360(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        Percent;                                           // 0x0368(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        PickingUp;                                         // 0x0370(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class ABP_FirstPersonCharacter_C*             Hrac;                                              // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void HidePB();
	void Set_(double Percent_0, class USoundBase* Sound, double Kedy_zrychlit, bool* done_);
	void PreConstruct(bool IsDesignTime);
	void End_PB();
	void ExecuteUbergraph_WB_RoundProgressBar(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WB_RoundProgressBar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WB_RoundProgressBar_C")
	}
	static class UWB_RoundProgressBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_RoundProgressBar_C>();
	}
};
DUMPER7_ASSERTS_UWB_RoundProgressBar_C;

SDK_NAMESPACE_END
