#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace ABP_FP_Copy { struct FAnimBlueprintGeneratedConstantData; }


namespace NPCUnarmed
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_Unarmed
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}
